const {test, expect} = require('@playwright/test')

test('gallery cards open from their artwork and refresh saved progress across tabs', async ({page, context}) => {
    await page.goto('/index.html')
    const card = page.locator('article[data-game="2048"]')
    const link = card.locator('a')
    await expect(link).toHaveAccessibleName('Play · 2048')
    const game = await context.newPage()
    await game.goto('/2048.html')
    const board = game.locator('game-2048 .board')
    await board.focus()
    await game.keyboard.press('ArrowLeft')
    await game.keyboard.press('ArrowDown')
    await expect(link).toHaveText('Continue')
    await expect(link).toHaveAccessibleName('Continue · 2048')
    await game.close()
    const preview = card.locator('.preview')
    await preview.scrollIntoViewIfNeeded()
    const artwork = await preview.boundingBox()
    await page.mouse.click(artwork.x + artwork.width / 2, artwork.y + artwork.height / 2)
    await expect(page).toHaveURL(/\/2048\.html$/)
    await expect(page.locator('game-2048 .undo')).toBeEnabled()
    await page.goBack()
    await expect(page.locator('article[data-game="2048"] a')).toHaveText('Continue')
})

test('drawer contains keyboard focus including nested settings controls', async ({page}) => {
    await page.goto('/index.html')
    await page.locator('offline-shell .menu-btn').click()
    const drawer = page.locator('offline-drawer')
    const brand = drawer.locator('.brand')
    const source = drawer.locator('footer a')
    await source.focus()
    await page.keyboard.press('Tab')
    await expect(brand).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(source).toBeFocused()
    await drawer.locator('[data-value="dark"]').focus()
    await page.keyboard.press('Escape')
    await expect(page.locator('offline-shell .menu-btn')).toBeFocused()
    await expect(drawer.locator('aside')).toHaveAttribute('inert', '')
})

test('short screens keep boards readable and allow scrolling to the remaining controls', async ({page}) => {
    await page.setViewportSize({width: 844, height: 390})
    for (const game of ['sudoku', 'nonogram', 'minesweeper']) {
        await page.goto(`/${game}.html`)
        await page.waitForFunction(() => Number(document.querySelector('offline-shell')?._fitSurface?.dataset.fitScale) >= .8)
        const main = page.locator('offline-shell main')
        expect(await main.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
        const board = page.locator(`${game}-game .board`)
        await board.locator('.cell').last().scrollIntoViewIfNeeded()
        await expect(board.locator('.cell').last()).toBeInViewport()
        if (game === 'sudoku') {
            const erase = page.locator('sudoku-game .erase')
            await erase.scrollIntoViewIfNeeded()
            await expect(erase).toBeInViewport()
        }
        if (game === 'minesweeper') {
            const flag = page.locator('minesweeper-game .flag')
            await flag.scrollIntoViewIfNeeded()
            await expect(flag).toBeInViewport()
        }
        expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(390)
        await page.setViewportSize({width: 844, height: 400})
        await expect.poll(() => page.evaluate(() => Number(document.querySelector('offline-shell')._fitSurface.dataset.fitScale))).toBeGreaterThanOrEqual(.8)
        await page.setViewportSize({width: 844, height: 390})
    }
})
